import Business from "@/components/Business";
import Hero from "@/components/Hero";
import ListedEvent from "@/components/ListedEvent";
import Testimonials from "@/components/Testimonials";
import Works from "@/components/Works";
import Head from 'next/head'
import axios from 'axios'
import { useState, useEffect } from 'react'

export default function Index2() {
    const [auth, setAuth] = useState(false);

    const retrievecookies = () => {
    axios.get('/api/votingcookieauthenticateAPI')
    .then (res => {
      if (res.status === 200) {
        setAuth(true)
      }
      else {
        console.log('Try again!')
        setAuth(false)
      }
    })
    .catch(err => {
      console.log(err)
      setAuth(false)
    })
    }
   
    useEffect(() => {
       retrievecookies();
     }, []);

if (auth){
  return (
    <>
    <Head>
    <title>Vote</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <div className="bg-[#F1F5F6] w-full">
      <div className="bg-[#F1F5F6] flex justify-center items-start">
        <div className="xl:max-w-[1280px] w-full">
          <Hero />
        </div>
      </div>

      <div className="flex bg-[#F1F5F6] sm:px-16 px-6 justify-center items-start">
        <div className="xl:max-w-[1280px] w-full">
          <Business />
          <ListedEvent />
          <Works />
          <Testimonials />
        </div>
      </div>
    </div>
    </>
  )
  }
  else {
    return (
        <div className='lg:text-[240%] md:text-[240%] text-[200%] p-[12%] font-[600] text-center text-[#b00] bg-[#224]'>You must be authenticated to access this page!!</div>
    )
  }
}